name: Releases

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-ext-windows:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          path-type: inherit
          install: >-
            git
            curl

      - shell: msys2 {0}
        run: |
          pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-make mingw-w64-x86_64-gcc mingw-w64-x86_64-curl --noconfirm
          pacman -S curl libcurl openssl-devel libcurl-devel autoconf texinfo mingw-w64-x86_64-libtool --noconfirm

          which make
          /usr/bin/make

      - name: Upload windows Artifact ext
        uses: actions/upload-artifact@v4
        with:
          name: txiki-windows
          path: ./build/tjs.exe

  build-ext-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: build macos-latest
        run: |
          brew install cmake autoconf automake libtool texinfo
          make

      - name: Upload macos Artifact ext
        uses: actions/upload-artifact@v4
        with:
          name: txiki-macos
          path: ./build/tjs

  build-ext-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: build ubuntu-latest
        run: |
          sudo apt install libcurl4-openssl-dev build-essential cmake autoconf texinfo libtool -y
          make

      - name: Upload ubuntu Artifact
        uses: actions/upload-artifact@v4
        with:
          name: txiki-linux
          path: ./build/tjs

  release:
    needs: [build-ext-windows, build-ext-macos, build-ext-ubuntu]
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: txiki-build
          pattern: txiki-*
          merge-multiple: true

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "txiki-build/*"
