name: Releases

# test

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - master

jobs:
  build-windows-x86_64:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          path-type: inherit
          install: >-
            curl
            make
            cmake

      - shell: msys2 {0}
        run: |
          pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-make mingw-w64-x86_64-curl libcurl openssl-devel libcurl-devel autoconf texinfo mingw-w64-x86_64-libtool --noconfirm
          make

          mkdir ./txiki-windows-x86_64
          cp build//tjs.exe ./txiki-windows-x86_64/tjs.exe
          cd txiki-windows-x86_64
          ldd ./tjs.exe | grep -v '=> /c/Windows/.*' | awk '{print $3}' | xargs -I '{}' cp -v '{}' .

      - name: Upload windows x86_64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: txiki-windows-x86_64
          path: ./txiki-windows-x86_64

  build-macos-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: build macos-latest
        run: |
          brew install cmake autoconf automake libtool texinfo
          make

          mkdir ./txiki-macos-arm64
          cp build/tjs ./txiki-macos-arm64/tjs

      - name: Upload macos arm64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: txiki-macos-arm64
          path: ./txiki-macos-arm64

  build-macos-x86:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: build macos-latest
        run: |
          brew install cmake autoconf automake libtool texinfo
          make

          mkdir ./txiki-macos-x86
          cp build/tjs ./txiki-macos-x86/tjs

      - name: Upload macos x86 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: txiki-macos-x86
          path: ./txiki-macos-x86

  release:
    needs: [build-windows-x86_64, build-macos-x86, build-macos-arm64]
    name: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: txiki-*
          merge-multiple: false

      - name: compress
        run: |
          cd dist
          for dir in */; do zip -r "${dir%/}.zip" "$dir"; done

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "dist/*.zip"
